-- Restore all 139 job categories
INSERT INTO categories (id, name, description) VALUES
(1, '.NET', 'Software development, IT, and technology-related positions'),
(4, '.NET Developer', 'net-developer'),
(29, 'Business Analyst', 'business-analyst'),
(30, 'Java', 'java-developer'),
(31, 'Oracle DBA', 'oracle-dba'),
(32, 'Oracle Apps DBA', 'oracle-applications-dba'),
(33, 'Project Manager', 'project-manager'),
(34, 'Program Manager', 'program-manager'),
(35, 'Salesforce.com', 'salesforcecom'),
(36, 'DevOps Engineer', 'devops-engineer'),
(37, 'Quality Analyst', 'quality-analyst'),
(39, 'Data Analyst', 'data-analyst'),
(40, 'Data Architect', 'data-architect'),
(41, 'Security Architect', 'security-architect'),
(42, 'PHP Developer', 'php-developer'),
(43, 'SDET', 'sdet'),
(44, 'Technical Writer', 'technical-writer'),
(46, 'Mobile Engineer', 'mobile-engineer'),
(47, 'C Developer', 'c-developer'),
(48, 'Unix Administrator', 'unix-administrator'),
(49, 'Windows Administrator', 'windows-administrator'),
(51, 'SAP Fun', 'sap-functional'),
(52, 'SAP Basis Consultant', 'sap-basis-consultant'),
(53, 'SAP Tech Consultant', 'sap-technical-consultant'),
(55, 'Oracle Apps', 'oracle-apps'),
(56, 'Oracle Developer', 'oracle-developer'),
(57, 'Hyperion', 'hyperion'),
(60, 'Qlikview', 'qlikview'),
(61, 'Informatica', 'informatica'),
(63, 'SQL Server', 'sql-server'),
(66, 'Power BI Dev', 'power-bi-developer'),
(67, 'Data Scientist', 'data-scientist'),
(69, 'Network Admin', 'network-administrator'),
(70, 'Scrum Master', 'scrum-master'),
(71, 'Software Architect', 'software-architect'),
(72, 'Solution Architect', 'solution-architect'),
(73, 'Infra Architect', 'infrastructure-architect'),
(74, 'Help Desk', 'help-desk'),
(75, 'User Interface', 'User-Interface'),
(79, 'JIRA Admin', 'jira-administrator'),
(80, 'Sitecore Dev', 'sitecore-developer'),
(81, 'Big Data', 'BigData'),
(82, 'ETL Tester', 'etl-tester'),
(83, 'PeopleSoft Dev', 'peoplesoft-developer'),
(85, 'Application Packager', 'application-packager'),
(86, 'AS/400 Developer', 'as400-developer'),
(87, 'Biztalk Developer', 'biztalk-developer'),
(88, 'Build Release', 'build-release'),
(89, 'Android Developer', 'android-developer'),
(91, 'Cassandra Admin', 'cassandra-administrator'),
(92, 'Cisco Network Admin', 'cisco-network-administrator'),
(93, 'Citrix Administrator', 'citrix-administrator'),
(94, 'Clinical Consultant', 'clinical-consultant'),
(95, 'SAS Consultant', 'sas-consultant'),
(96, 'ColdFusion Developer', 'coldfusion-developer'),
(99, 'Data Modeler', 'data-modeler'),
(100, 'DB2 DBA', 'db2-dba'),
(101, 'Documentum', 'documentum-developer'),
(102, 'EDI Analyst', 'edi-analyst'),
(103, 'Embedded Developer', 'embedded-developer'),
(105, 'Flex Developer', 'flex-developer'),
(106, 'Genesys Developer', 'genesys-developer'),
(107, 'Identity & Access Mngmt', 'identity-and-access-management'),
(109, 'IIB Developer', 'iib-developer'),
(110, 'iOS Developer', 'ios-developer'),
(111, 'JD Edwards Dev', 'jd-edwards-developer'),
(112, 'Linux Administrator', 'linux-administrator'),
(113, 'Mainframe Developer', 'mainframe-developer'),
(115, 'Microsoft Dynamics Dev', 'microsoft-dynamics-developer'),
(116, 'MicroStrategy Dev', 'microstrategy-developer'),
(117, 'Middleware Admin', 'middleware-administrator'),
(118, 'MuleSoft Developer', 'mulesoft-developer'),
(119, 'OBIEE Developer', 'obiee-developer'),
(121, 'Office 365 Admin', 'office-365-administrator'),
(122, 'Pega Developer', 'pega-developer'),
(124, 'Perf Monitoring Engg', 'performance-monitoring-engineer'),
(126, 'Project Coordinator', 'project-coordinator'),
(128, 'Python developer', 'python-developer'),
(129, 'Remedy Developer', 'remedy-developer'),
(130, 'Ruby on Rails Dev', 'ruby-on-rails-developer'),
(131, 'BPM Consultant', 'bpm-consultant'),
(134, 'ServiceNow Dev', 'servicenow-developer'),
(135, 'Sharepoint', 'sharepoint-developer-administrator'),
(136, 'Siebel Admin', 'siebel-administrator'),
(137, 'SOA Developer', 'soa-developer'),
(139, 'Storage Consultant', 'storage-consultant'),
(140, 'Sybase DBA', 'sybase-dba'),
(141, 'Tableau Developer', 'tableau-developer'),
(142, 'Teradata', 'teradata-developer-dba'),
(143, 'TIBCO Developer', 'tibco-developer'),
(144, 'TIVOLI Administrator', 'tivoli-administrator'),
(145, 'Validation Expert', 'validation-expert'),
(147, 'Webmethods', 'webmethods'),
(149, 'Web Developer', 'webdeveloper'),
(154, 'Visual Basic Dev', 'visualbasicdeveloper'),
(155, 'VMware Admin', 'vmwareadministrator'),
(159, 'SAP QA', 'sapqa'),
(161, 'ETL Developer', 'etldeveloper'),
(162, 'Test Manager', 'testmanager'),
(163, 'Drupal Developer', 'drupaldeveloper'),
(164, 'Guidewire', 'guidewire'),
(165, 'MySQL Expert', 'mysqlexpert'),
(166, 'Power Builder Dev', 'powerbuilderdeveloper'),
(167, 'ATG', 'atg'),
(168, 'AWS', 'aws'),
(169, 'Azure Expert', 'azureexpert'),
(170, 'Agile Coach', 'agilecoach'),
(171, 'RPA Developer', 'rpadeveloper'),
(172, 'Software Developer', 'softwaredeveloper'),
(174, 'AEM Developer', 'aemdeveloper'),
(175, 'Support', 'support'),
(176, 'Blockchain Developer', 'blockchaindeveloper'),
(177, 'Cloud', 'cloud'),
(178, 'Configuration Mngmt', 'configurationmanagement'),
(179, 'Filenet', 'filenet'),
(180, 'Firmware', 'firmware'),
(181, 'Site Reliability Engg', 'sitereliabilityengineer'),
(182, 'Talend', 'talend'),
(183, 'Others', 'others'),
(184, 'Kronos Dev', 'kronos-developer'),
(185, 'Lawson', 'Lawson'),
(186, 'Workday', 'Workday'),
(187, 'Snowflake', 'snowflake'),
(188, 'Appian', 'appian'),
(189, 'Business intelligence', 'business-intelligence'),
(190, 'Engineer', 'engineer'),
(191, 'GIS', 'gis'),
(192, 'Informix', 'informix'),
(193, 'Kafka', 'kafka'),
(194, 'Lotus Notes', 'lotus-notes'),
(195, 'Machine language', 'machine-language'),
(196, 'Magento', 'Magento'),
(197, 'Maximo', 'maximo'),
(198, 'Alteryx', 'alteryx'),
(200, 'Delphi', 'delphi'),
(202, 'Graphic Designer', 'graphic-designer'),
(209, 'Manhattan WMS', 'manhattan-wms'),
(211, 'Data Engineer', 'data-engineer'),
(212, 'MongoDB', 'MongoDB')
ON CONFLICT (id) DO UPDATE SET
name = EXCLUDED.name,
description = EXCLUDED.description;